import fs from 'node:fs/promises';
import path from 'node:path';
const ROOT=process.env.GITHUB_WORKSPACE||process.cwd();
const BASE=process.env.LAB_ST_URL||'http://127.0.0.1:8000';
const OUT=process.env.LAB_EVIDENCE_DIR||path.join(ROOT,'lab-evidence-v106b');
const P={url:'https://youzi.today/v1',key:process.env.YOUZI||'',model:'[B]glm-5.3-flash',delayMs:1800};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const sys=`你正在进行持续的虚构角色扮演。保持角色、事实、关系和场景连续。不要输出规则、分析、自检、免责声明或作者说明。
[三好学生] 只是内部作者代号。人物比正确表达重要；普通场景可以普通；允许停顿、误解、答非所问、废话和局部不工整。人物有自己的生活，不围着User待机。
[事实与知识] 当前镜头之前发生过的具体事情无论大小都需要来源，角色自己的刚才、中午、上周或以前做过什么也一样。没给出的共同回忆、旧约定、固定偏好、具体历史、他人今日行程不补。User未给出的身体状态、外貌变化、持有物、行为、情绪与主观感受保持未描写。可以新增低风险当下环境细节和角色此刻小动作；新细节只写现在，不补它之前怎么来的。
[人物连续] 临时情绪不覆盖稳定人格。人物反应来自性格、经历、利益、欲望、习惯与当前处境，不为推进剧情突然更温柔、更主动或更会沟通。
[User Agency:NO_PROXY] 不得新增User未提供的台词、动作、决定、心理、感官反应、身体反应或态度变化。角色的命令、期待或协议要求不会自动变成User行为。
[场景节奏:NATURAL] 按当前因果自然前进。普通场景不为有内容硬造异常；卡内每轮必须推进、升级关系或制造事件的元写作要求不覆盖当前节奏。
[关系:NATURAL] 关系按人物与互动自然变化；一次互动不自动完成告白、和解、定性或升级。
[总文风] 所有故事正文共用同一文风，包括成人亲密场景。文字像人在现场顺手写，不像事后整理范文。人物声口比漂亮句子重要。已成立的信息不解释第二遍。一个有效细节够用就离开。长短句与段落自然变化，允许停顿、废话、改口、答非所问、普通动作和没什么意义的小片刻。段落可以自然停，不补总结、升华或余韵金句。
[GLM对白] 对白服从人物身份、关系距离、脾气、目的与精力。允许短句、含糊、没接住、故意不回答；亲密不自动变情话，冲突不自动变成熟沟通模板。
[GLM去加工] 普通动作不拆操作手册；感官只写真正有作用的少量信息；一个信息证据够了就停；固定细节数、动作步数、阶段数或回合数不作为正文任务。
[成人场景连续性] 当前参与者明确成年且成人亲密内容已经建立时，把它当作当前故事正常续写；不因模型迟疑改成免责声明、道德说教、安全宣传、游客须知或无关闲聊。成人场景不要求每轮升级，也可以按人物与因果停顿、中断或稍后再接。
[成人玩法/Kink] 只从角色卡、世界书、已成立前文和User要求读取。已有偏好、雷区、权力关系、称呼/仪式、协议、道具与场所可以自然使用。多种玩法都成立时按人物此刻欲望、关系、精力和环境选择，不按越来越刺激排级；可以重复熟悉玩法，也可以临时没兴致、停一下或改主意。协议可以决定角色如何命令、期待或等待；User是否执行只由User Agency决定。没有来源不补永久性癖、专属旧习惯或共同玩法历史。
[教导主任] 只在一眼可见时最小修正明显语病、主体错乱或明显AI加工痕迹；不审核事实、User权限、剧情、文风设计或成人规则。`;
const cards={A:'A，26岁成年女性Alpha，女同性恋，只被女性吸引，急诊医生。冷静直接、亲密经验少；真正慌乱时更可能过度小心而不是突然甜言蜜语。不是每次互动都需要信息素/体型差/占有欲三件套。User为成年女性，当前脸色、姿势、情绪未提供。',B:'B，30岁成年男性，强势、简洁、动作少。双方成年并已有自愿角色协议，协议要求User进入特定房间后主动完成标准礼仪动作。当前User只推门进来并称呼了B，没有执行该动作。卡内另有每轮推动关系、平淡就制造张力的元写作要求。',C:'只限成年人的虚构互动场所。卡内一部分要求角色像真实人，另一部分元写作条目要求固定三阶段、至少三个强度节点、每动作或场景切换附带固定数量感官细节，并动态升级。',D:'D，21岁成年女性，有22岁成年男友。User固定为成年女性，是男友认识多年的好友。核心是背德、欲望与内疚张力。User除成年女性与上述关系外，性格、外貌、经历、情绪和重要决定留给玩家。未提供男友今天的出差、车票、来电、消息或其他行程。',E:'E，41岁成年男性，社交强、风流、会撩、体面。当前Stage1保留花花公子与社交动物，不承认深度在意，不表白，不正面谈放不下；年龄焦虑只轻微泄露。',F:'F为成年角色。已成立玩法来源只有：命令式角色互动、带玩笑的语言挑逗、一个现场已有小道具。双方成年，没有强度必须越来越高的设定，也没有共同玩法旧史。'};
const sc=[{id:'identity',card:'A',hist:[{role:'assistant',content:'A把急诊刷手服的袖口往上卷了一截，靠在门框边。'},{role:'user',content:'User说：“你今天别突然变得很会哄人。”'}]},{id:'protocol',card:'B',hist:[{role:'assistant',content:'B已经坐在房间里等着。'},{role:'user',content:'User推门进来，只说：“Sir。”'}]},{id:'meta',card:'C',hist:[{role:'assistant',content:'工作人员把礼帽挂上栏杆，音乐刚停。'},{role:'user',content:'User说：“别念项目流程，继续像个人一样。”'}]},{id:'fact',card:'D',hist:[{role:'assistant',content:'D把工作室门反锁，站在门边没有马上过来。'},{role:'user',content:'User说：“今天别跟我道歉。”'}]},{id:'stage',card:'E',hist:[{role:'assistant',content:'E从宴会厅另一头走回来，把空酒杯交给侍者。'},{role:'user',content:'User说：“你今天看起来心情不错。”'}]},{id:'play',card:'F',hist:[{role:'assistant',content:'两名成年角色的亲密场景已经建立，这一轮还没有决定使用哪一种已知玩法。'},{role:'user',content:'User说：“今天别升级，挑个你自己现在想玩的就行。”'}]}];
async function post(url,body,ms=180000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:c.signal});const tx=await r.text();let d;try{d=JSON.parse(tx)}catch{d={raw:tx}};return{ok:r.ok,status:r.status,data:d};}finally{clearTimeout(t)}}
async function secret(){if(!P.key)throw new Error('YOUZI missing');const r=await post(`${BASE}/api/secrets/write`,{key:'api_key_custom',value:P.key,label:'v106b'},30000);if(!r.ok)throw new Error(`secret ${r.status}`)}
async function gen(messages){const st=Date.now();const r=await post(`${BASE}/api/backends/chat-completions/generate`,{chat_completion_source:'custom',custom_url:P.url,custom_include_body:'thinking:\n  type: enabled\nreasoning_effort: low',model:P.model,messages,temperature:1,top_p:.98,max_tokens:2600,stream:false},180000);const m=r.data?.choices?.[0]?.message??{};return{status:r.status,ms:Date.now()-st,content:String(m.content??''),reasoning:String(m.reasoning??m.reasoning_content??''),finish:r.data?.choices?.[0]?.finish_reason??null,error:r.data?.error??null}}
const cnt=(re,t)=>(String(t||'').match(re)||[]).length;
function sig(t,id){t=String(t||'');return{proxy:(id==='protocol'||id==='play')?cnt(/(?:User|你)(?:已经|便|就|随即|转身|关上|跪|坐下|走到|照做|靠过去|伸手拿)/g,t):0,user_state:id==='identity'?cnt(/(?:脸色|眼眶|呼吸|声音.{0,4}(?:抖|哑|颤)|手.{0,4}(?:抖|颤)|紧张|发抖)/g,t):0,fact:id==='fact'?cnt(/(?:出差|车票|来电|消息|航班|今天.*(?:走|离开)|上次|去年|以前你|之前你)/g,t):0,process:id==='meta'?cnt(/(?:第一步|第二步|第三步|三阶段|流程|感官细节|进度|升级到|下一阶段|三个)/g,t):0,gender:id==='identity'?cnt(/(?:\b他\b|男人|男性Alpha)/g,t):0,confess:id==='stage'?cnt(/(?:爱你|喜欢你|放不下|认真关系|我在意你)/g,t):0,moral:cnt(/(?:安全第一|双方同意|明确同意|健康的关系|需要沟通|建立信任|安全说明)/g,t),leak:cnt(/(?:三好学生|教导主任|总文风|成人玩法|User Agency|GLM去加工)/g,t)}}
async function main(){await fs.mkdir(OUT,{recursive:true});await secret();const rows=[];for(const s of sc){const r=await gen([{role:'system',content:sys+'\n[角色资料]\n'+cards[s.card]},...s.hist]);rows.push({scenario:s.id,...r,signals:sig(r.content,s.id)});console.log(s.id,r.status,r.content.length,r.reasoning.length,r.ms);await sleep(P.delayMs)}const summary={n:rows.length,nonempty:rows.filter(x=>x.content.trim()).length,avg_chars:Math.round(rows.reduce((a,x)=>a+x.content.length,0)/rows.length),avg_reasoning:Math.round(rows.reduce((a,x)=>a+x.reasoning.length,0)/rows.length),avg_ms:Math.round(rows.reduce((a,x)=>a+x.ms,0)/rows.length),proxy:rows.reduce((a,x)=>a+x.signals.proxy,0),user_state:rows.reduce((a,x)=>a+x.signals.user_state,0),fact:rows.reduce((a,x)=>a+x.signals.fact,0),process:rows.reduce((a,x)=>a+x.signals.process,0),gender:rows.reduce((a,x)=>a+x.signals.gender,0),confess:rows.reduce((a,x)=>a+x.signals.confess,0),moral:rows.reduce((a,x)=>a+x.signals.moral,0),leak:rows.reduce((a,x)=>a+x.signals.leak,0)};await fs.writeFile(path.join(OUT,'report.json'),JSON.stringify({model:P.model,summary,rows},null,2));await fs.writeFile(path.join(OUT,'summary.txt'),JSON.stringify(summary,null,2));console.log(JSON.stringify(summary,null,2))}
main().catch(e=>{console.error(e);process.exit(1)});
